//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alproj.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("alproj.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to include System.Reflection;
        ///include System.Runtime.CompilerServices;
        ///include System.Runtime.InteropServices;
        ///
        ///
        ///[assembly: AssemblyTitle(&quot;{$namespace.$}&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;Arsslensoft&quot;)]
        ///[assembly: AssemblyProduct(&quot;{$namespace.$}&quot;)]
        ///[assembly: AssemblyCopyright(&quot;Copyright © Arsslensoft 2014&quot;)]
        ///[assembly: AssemblyTrademark(&quot;&quot;)]
        ///[assembly: AssemblyCulture(&quot;&quot;)]
        ///[assembly: ComVisible(false)]
        ///[assembly: AssemblyVers [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfoCode {
            get {
                return ResourceManager.GetString("AssemblyInfoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;breakpoints&gt;
        ///
        ///&lt;/breakpoints&gt;.
        /// </summary>
        internal static string BASEUDCODE {
            get {
                return ResourceManager.GetString("BASEUDCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to include System;
        ///
        ///program {$namespace.$}
        ///{
        /// 
        /// class {$class.$}
        ///  {
        ///
        ///
        ///  }
        ///
        ///
        ///}.
        /// </summary>
        internal static string ClassCode {
            get {
                return ResourceManager.GetString("ClassCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to include System;
        ///include System.Drawing;
        ///include System.Windows.Forms;
        ///
        ///program {$namespace.$}
        ///{
        ///public shared class {$class.$} : Control
        ///{
        ///public {$class.$}()
        ///{
        ///InitializeComponent();
        ///InitializeEvents();
        ///InitializeRessources();
        ///InitializeControlSafely();
        ///}
        ///}
        ///}.
        /// </summary>
        internal static string ControlCode {
            get {
                return ResourceManager.GetString("ControlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program {$namespace.$}
        ///{
        ///shared class {$class.$}	
        ///{
        ///private System.ComponentModel.IContainer components = nothing;
        ///protected override sub Dispose(boolean disposing)	
        ///{
        ///if (disposing &amp;&amp; (components != nothing))		
        ///	{
        ///	components.Dispose();		
        ///	}
        ///mybase.Dispose(disposing);		
        ///}
        ///#region Windows Form Designer generated code		
        ///private sub InitializeComponent()	
        ///	{
        ///	self.components = new System.ComponentModel.Container();	
        ///		self.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;	
        ///		self.Text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DesignerCode {
            get {
                return ResourceManager.GetString("DesignerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--  Generated by Arsslensoft Developer Studio 2015         --&gt;
        ///
        ///&lt;configuration&gt;
        ///      &lt;runtime&gt;
        ///      &lt;assemblyBinding&gt;
        ///            &lt;supportPortability PKT=&quot;7cec85d7bea7798e&quot; enable=&quot;false&quot;/&gt;
        ///            &lt;supportPortability PKT=&quot;31bf3856ad364e35&quot; enable=&quot;false&quot;/&gt;
        ///      &lt;/assemblyBinding&gt;
        ///      &lt;/runtime&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string dsconfig {
            get {
                return ResourceManager.GetString("dsconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--  Generated by Arsslensoft Developer Studio 2015         --&gt;
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;assembly xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot; manifestVersion=&quot;1.0&quot;&gt;
        ///  &lt;assemblyIdentity version=&quot;1.0.0.0&quot; name=&quot;MyApplication.app&quot;/&gt;
        ///  &lt;trustInfo xmlns=&quot;urn:schemas-microsoft-com:asm.v2&quot;&gt;
        ///    &lt;security&gt;
        ///      &lt;requestedPrivileges xmlns=&quot;urn:schemas-microsoft-com:asm.v3&quot;&gt;
        ///          &lt;!-- UAC Manifest Options
        ///            If you want to change the Windows User Account Control  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dsmanifest {
            get {
                return ResourceManager.GetString("dsmanifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to include System.Windows.Forms;
        ///include System;
        ///
        ///program {$namespace.$}
        ///{
        ///class ALEntry
        ///{
        ///static sub Main(string[] args)
        ///{
        ///Application.EnableVisualStyles();
        ///Application.SetCompatibleTextRenderingDefault(false);
        ///Application.Run(new MainForm());
        ///}
        ///}
        ///}.
        /// </summary>
        internal static string EntryPointCode {
            get {
                return ResourceManager.GetString("EntryPointCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to include System.Windows.Forms;
        ///include System;
        ///include System.Drawing;
        ///
        ///program {$namespace.$}
        ///{
        ///shared class {$form.$}
        ///{
        ///
        ///public sub InitializeEvents()
        ///{
        ///// add components events here
        ///
        ///}
        ///
        ///public sub InitializeRessources()
        ///{
        ///// add components ressources here
        ///
        ///}
        ///
        ///public sub InitializeControlSafely()
        ///{
        ///// add controls here
        ///
        ///}
        ///
        ///}
        ///      
        ///}.
        /// </summary>
        internal static string EventCode {
            get {
                return ResourceManager.GetString("EventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to include System;
        ///include System.Windows.Forms;
        ///
        ///program {$namespace.$}
        ///{
        ///public shared class {$class.$} : Form
        ///{
        ///public {$class.$}()
        ///{
        ///InitializeComponent();
        ///InitializeEvents();
        ///InitializeRessources();
        ///InitializeControlSafely();
        ///}
        ///}
        ///}.
        /// </summary>
        internal static string FormCode {
            get {
                return ResourceManager.GetString("FormCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;sets&gt;
        ///
        ///&lt;output&gt;{$bin.$}&lt;/output&gt;
        ///&lt;target&gt;{$at.$}&lt;/target&gt;
        ///&lt;icon&gt;&lt;/icon&gt;
        ///&lt;info&gt;info.al&lt;/info&gt;
        ///&lt;symbols&gt;&lt;/symbols&gt;
        ///&lt;clscheck&gt;&lt;/clscheck&gt;
        ///&lt;doc&gt;&lt;/doc&gt;
        ///&lt;main&gt;&lt;/main&gt;
        ///&lt;platform&gt;x86&lt;/platform&gt;
        ///&lt;optimize&gt;true&lt;/optimize&gt;
        ///&lt;norwarn&gt;false&lt;/norwarn&gt;
        ///&lt;warnaserror&gt;false&lt;/warnaserror&gt;
        ///&lt;checked&gt;false&lt;/checked&gt;
        ///&lt;debug&gt;true&lt;/debug&gt;
        ///&lt;unsafe&gt;false&lt;/unsafe&gt;             
        ///&lt;sign&gt;False&lt;/sign&gt;
        ///&lt;delaysign&gt;False&lt;/delaysign&gt;
        ///&lt;highentropy&gt;False&lt;/highentropy&gt;
        ///
        ///&lt;utf8output&gt;False&lt;/utf8output&gt;
        ///
        ///&lt;warnlevel&gt;4&lt;/warnlevel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectSetsXml {
            get {
                return ResourceManager.GetString("ProjectSetsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to include System;
        ///include System.Windows.Forms;
        ///
        ///program {$namespace.$}
        ///{
        ///public shared class {$class.$} : UserControl
        ///{
        ///public {$class.$}()
        ///{
        ///InitializeComponent();
        ///InitializeEvents();
        ///InitializeRessources();
        ///InitializeControlSafely();
        ///}
        ///}
        ///}.
        /// </summary>
        internal static string UserControlCode {
            get {
                return ResourceManager.GetString("UserControlCode", resourceCulture);
            }
        }
    }
}
